service: filmx-python-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  stage: dev
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: 5432

functions:
  getUsers:
    handler: src/api/get_users/handler.handler
    events:
      - httpApi:
          path: /users
          method: get

  activateSubscription:
    handler: src/api/activate_subscription/handler.handler
    events:
      - httpApi:
          path: /subscriptions/activate
          method: post

  payment:
    handler: src/api/payment/handler.handler
    events:
      - httpApi:
          path: /payments
          method: post

package:
  exclude:
    - node_modules/**
    - frontend/**
    - tests/**
    - infra/**
    - .github/**
    - README.md

custom:
  serverless-offline:
    httpPort: 4000
