name: Deploy Lambda

on:
  push:
    branches:
      - main        # Deploy to PROD on push to main
      - develop     # Deploy to DEV on push to develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t package/
          cp -r main.py src package/
          cd package && zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda (DEV)
        if: github.ref == 'refs/heads/develop'
        run: |
          aws lambda update-function-code \
            --function-name manualFunction:dev \
            --zip-file fileb://lambda.zip

      - name: Deploy to Lambda (PROD)
        if: github.ref == 'refs/heads/main'
        run: |
          aws lambda update-function-code \
            --function-name manualFunction \
            --zip-file fileb://lambda.zip
